apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ default .Values.target.name .Values.nameOverride }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.secretStoreRef.kind }}
    name: {{ .Values.secretStoreRef.name }}
  target:
    name: {{ .Values.target.name }}
    creationPolicy: {{ .Values.target.creationPolicy }}
  data:
    {{- range .Values.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
    {{- end }}
