# Default values for todo-app.

replicaCount: 1

frontend:
  image:
    repository: ghcr.io/wedgehov/todo-frontend
    pullPolicy: IfNotPresent # This should be set in the environment-specific values file.
    tag: "" # e.g., "v1.0.7"

backend:
  image:
    repository: ghcr.io/wedgehov/todo-api
    pullPolicy: IfNotPresent # This should be set in the environment-specific values file.
    tag: "" # e.g., "v1.0.7"

database:
  image:
    repository: postgres
    tag: "16"
  storage: 1Gi
  user: todo_user
  dbName: todo_db
  secretName: todo-app-db-secret
  passwordKey: postgres-password

ingress:
  enabled: true
  className: nginx
  host: todo-app.example.com # A generic placeholder

resources: {}
databaseResources: {}

networkPolicy:
  enabled: false # Set to true in environment values to enable

storageClassName: nutanix-volume