apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
spec:
  ports:
    - port: 5432
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-db-v2
spec:
  serviceName: {{ .Release.Name }}-db
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: database
        image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
        envFrom:
        - secretRef:
            name: {{ .Values.database.secretName }}
        ports:
        - containerPort: 5432
          name: postgres
        resources:
{{ toYaml .Values.databaseResources | indent 10 }}
        volumeMounts:
        - name: db-data-v2
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: db-data-v2
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: {{ .Values.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.database.storage }}
