{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-db-access
spec:
  # This policy applies to pods with the 'database' label
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-database
  policyTypes:
  - Ingress
  ingress:
  - from:
    # 1. Only allow traffic from pods with the 'backend' label
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-backend
    ports:
    # 2. Only allow traffic on the PostgreSQL port
    - protocol: TCP
      port: 5432
{{- end }}

