apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: todo-app-db-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: onepassword-service-account
    kind: ClusterSecretStore
  target:
    name: todo-app-db-secret
  data:
  - secretKey: postgres-password
    remoteRef:
      key: todo-app-db
      property: password

