apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wedgehov/gitops.git
    targetRevision: HEAD
    path: rendered-manifests/dev/user/todo-app
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app-dev # Deploy the app to its own namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
