---
# Source: external-secret/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: todo-app-db-secret
  namespace: todo-app-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: todo-app-db-secret
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: todo-app-dev-postgres-password
