apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-service-account
spec:
  provider:
    onepassword:
      vaults:
        kubernetes-praksis: 1
      auth:
        token:
          name: onepassword-sa-token
          namespace: external-secrets
          key: 1password-token

