apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: onepassword-service-account
    kind: ClusterSecretStore
  target:
    name: kube-prometheus-stack-grafana
    creationPolicy: Merge
  data:
  - secretKey: admin-user
    remoteRef:
      key: grafana-admin
      property: username
  - secretKey: admin-password
    remoteRef:
      key: grafana-admin
      property: password

