apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    # Allow privileged pods like node-exporter to run in this namespace.
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
