# values/user/fm-todo-app/dev.yaml
# Environment-specific values for the fm-todo-app in dev.

# Helm Release name will be 'fm-todo-app-dev'
# The namespace will be 'fm-todo-app-dev'

# Image tags for the v1.0.0 release
frontend:
  image:
    tag: "v1.0.0"
backend:
  image:
    tag: "v1.0.0"

# Enable the network policy for security
networkPolicy:
  enabled: true

# Define the public-facing URL for the dev environment
ingress:
  host: fm-todo-app-dev.serit.dev

# Define resource requests and limits for the dev environment
resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

databaseResources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
