# Overrides for the 'fm-todo-app' in the 'dev' environment

# Use a global tag for both frontend and backend images
imageTag: "v1.5.0"

backend:
  aspnetcoreEnvironment: "Development"

ingress:
  host: fm-todo-app-dev.serit.dev

networkPolicy:
  enabled: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi

databaseResources:
  requests:
    cpu: 100m
    memory: 256Mi
