---
# Source: external-secret/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fm-todo-app-db-secret
  namespace: fm-todo-app-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: fm-todo-app-db-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: fm-todo-app-dev-postgres-user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: fm-todo-app-dev-postgres-password
    - secretKey: POSTGRES_DB
      remoteRef:
        key: fm-todo-app-dev-postgres-db
