apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wedgehov/gitops.git
    targetRevision: HEAD
    path: rendered-manifests/dev/platform/cloudflare-tunnel
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared # Deploy the tunnel to its own namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
