apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: monitoring-grafana
spec:
  externalSecretName: kube-prometheus-stack-grafana
  refreshTime: 1h
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: monitoring
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: azure-keyvault
    target:
      name: kube-prometheus-stack-grafana
      creationPolicy: Owner
    data:
      - secretKey: admin-user
        remoteRef:
          key: grafana-admin-user
      - secretKey: admin-password
        remoteRef:
          key: grafana-admin-password
