apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: todo-app-dev-db
spec:
  externalSecretName: todo-app-db-secret
  refreshTime: 1h
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: todo-app-dev
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: azure-keyvault
    target:
      name: todo-app-db-secret
      creationPolicy: Owner
    data:
      - secretKey: postgres-password
        remoteRef:
          key: todo-app-dev-postgres-password
