apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: fm-todo-app-main-db
spec:
  externalSecretName: fm-todo-app-db-secret
  refreshTime: 1h
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: fm-todo-app-main
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: azure-keyvault
    target:
      name: fm-todo-app-db-secret
      creationPolicy: Owner
    data:
      - secretKey: POSTGRES_USER
        remoteRef:
          key: fm-todo-app-main-postgres-user
      - secretKey: POSTGRES_PASSWORD
        remoteRef:
          key: fm-todo-app-main-postgres-password
      - secretKey: POSTGRES_DB
        remoteRef:
          key: fm-todo-app-main-postgres-db
