apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://vhgitopskvcdb1.vault.azure.net"
      tenantId: "b010c418-5a67-455d-909e-3963ee548a84"
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
