# Default values for fm-todo-app.

replicaCount: 1

image:
  repository: ghcr.io/wedgehov/frontend-mentor-todo-app
  pullPolicy: IfNotPresent
  tag: "" # This will be overridden by environment-specific values
  digest: "" # Optional immutable digest. If set, it takes precedence over tag.

backend:
  aspnetcoreEnvironment: "Production"

database:
  image:
    repository: postgres
    tag: "16-alpine"
  storage: 1Gi
  secretName: fm-todo-app-db-secret

ingress:
  enabled: true
  className: webapprouting.kubernetes.azure.com
  host: fm-todo-app.example.com # A generic placeholder

resources: {}
databaseResources: {}

networkPolicy:
  enabled: false # Set to true in environment values to enable

serviceMonitor:
  enabled: true

storageClassName: managed-csi
