{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    # This label allows Prometheus to discover the ServiceMonitor
    release: kube-prometheus-stack
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end }}


