{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-db-access
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-db
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-backend
    ports:
    - protocol: TCP
      port: 5432
{{- end }}


