---
# Source: fm-todo-app/templates/network-policy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fm-todo-app-db-access
spec:
  # This policy applies to pods with the 'database' label
  podSelector:
    matchLabels:
      app: fm-todo-app-db
  policyTypes:
  - Ingress
  ingress:
  - from:
    # 1. Only allow traffic from pods with the 'backend' label
    - podSelector:
        matchLabels:
          app: fm-todo-app-backend
    ports:
    # 2. Only allow traffic on the PostgreSQL port
    - protocol: TCP
      port: 5432
---
# Source: fm-todo-app/templates/backend-deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: fm-todo-app-backend
  labels:
    app: fm-todo-app-backend
    # This label is required for the ServiceMonitor to select this Service.
    release: kube-prometheus-stack
spec:
  type: ClusterIP
  # The port must be named for the ServiceMonitor to reference it.
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: fm-todo-app-backend
---
# Source: fm-todo-app/templates/database-statefulset.yaml
apiVersion: v1
kind: Service
metadata:
  name: fm-todo-app-db
spec:
  ports:
    - port: 5432
  clusterIP: None
  selector:
    app: fm-todo-app-db
---
# Source: fm-todo-app/templates/frontend-deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: fm-todo-app-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: fm-todo-app-frontend
---
# Source: fm-todo-app/templates/backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fm-todo-app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fm-todo-app-backend
  template:
    metadata:
      annotations:
        checksum/config: d256eb44c17df86c45dda6ab8e4b117784fdcd32ec8551986d2da1794dbc0001
      labels:
        app: fm-todo-app-backend
    spec:
      containers:
      - name: backend
        image: "ghcr.io/wedgehov/frontend-mentor-todo-app/todo-backend:v1.5.0"
        imagePullPolicy: IfNotPresent
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Host=fm-todo-app-db;Port=5432;Database=$(POSTGRES_DB);Username=$(POSTGRES_USER);Password=$(POSTGRES_PASSWORD)"
        # This tells the application where to send its traces. The standalone Tempo service
        # is named 'tempo-dev' and listens for OTLP traces on port 4317.
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://tempo-dev.monitoring.svc.cluster.local:4317"
        # Use the gRPC protocol for exporting traces.
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        # Explicitly set the service name to match the Grafana dashboard query.
        - name: OTEL_SERVICE_NAME
          value: "fm-todo-app-backend"
        # Ensure all traces are sampled and sent.
        - name: OTEL_TRACES_SAMPLER
          value: "always_on"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        envFrom:
        - secretRef:
            name: fm-todo-app-db-secret
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
---
# Source: fm-todo-app/templates/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fm-todo-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fm-todo-app-frontend
  template:
    metadata:
      annotations:
        checksum/config: d256eb44c17df86c45dda6ab8e4b117784fdcd32ec8551986d2da1794dbc0001
      labels:
        app: fm-todo-app-frontend
    spec:
      containers:
      - name: frontend
        image: "ghcr.io/wedgehov/frontend-mentor-todo-app/todo-frontend:v1.5.0"
        imagePullPolicy: IfNotPresent
        env:
        - name: API_URL
          value: "http://fm-todo-app-backend:8080"
        ports:
        - containerPort: 80
---
# Source: fm-todo-app/templates/database-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fm-todo-app-db-v5
spec:
  serviceName: fm-todo-app-db
  replicas: 1
  selector:
    matchLabels:
      app: fm-todo-app-db
  template:
    metadata:
      labels:
        app: fm-todo-app-db
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: database
        image: "postgres:16-alpine"
        envFrom:
        - secretRef:
            name: fm-todo-app-db-secret
        ports:
        - containerPort: 5432
          name: postgres
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - name: db-data-v5
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: db-data-v5
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: nutanix-volume
      resources:
        requests:
          storage: 1Gi
---
# Source: fm-todo-app/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fm-todo-app-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "fm-todo-app-dev.serit.dev"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fm-todo-app-frontend
            port:
              number: 80
---
# Source: fm-todo-app/templates/backend-servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fm-todo-app-backend
  labels:
    # This label is important! It allows the Prometheus instance
    # to discover this ServiceMonitor. It should match the
    # 'prometheus.prometheusSpec.serviceMonitorSelector' in your
    # kube-prometheus-stack values.
    release: kube-prometheus-stack
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: fm-todo-app-backend
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - fm-todo-app-dev
