# CRDs are installed separately during the bootstrap process, so we disable them here.
crds:
  enabled: false

grafana:
  # Use the existing grafana secret for admin credentials
  admin:
    existingSecret: "kube-prometheus-stack-grafana"

  ingress:
    enabled: true
    ingressClassName: "nginx" # Make sure this matches your Ingress Controller
    hosts:
      - grafana-dev.serit.dev
