# CRDs are installed separately during the bootstrap process, so we disable them here.
crds:
  enabled: false

grafana:
  # Use the existing grafana secret for admin credentials
  admin:
    existingSecret: "kube-prometheus-stack-grafana"

  ingress:
    enabled: true
    ingressClassName: "nginx" # Make sure this matches your Ingress Controller
    hosts:
      - grafana-dev.serit.dev

  # Configure grafana.ini settings to allow anonymous access.
  # This is great for making dashboards publicly viewable without a login.
  grafana.ini:
    auth.anonymous:
      enabled: true
      # The organization name for anonymous users.
      org_name: Main Org.
      # Assign the 'Viewer' role to anonymous users. They can view, but not edit.
      org_role: Viewer

# Tune down Prometheus resource usage for a smaller development cluster
# to prevent it from destabilizing the control-plane nodes.
prometheus:
  prometheusSpec:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
