---
# Source: external-secret/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: link-sharing-app-db-secret
  namespace: link-sharing-app-main
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: link-sharing-app-db-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: link-sharing-app-main-postgres-user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: link-sharing-app-main-postgres-password
    - secretKey: POSTGRES_DB
      remoteRef:
        key: link-sharing-app-main-postgres-db
