---
# Source: todo-app/templates/network-policy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: todo-app-db-access
spec:
  # This policy applies to pods with the 'database' label
  podSelector:
    matchLabels:
      app: todo-app-database
  policyTypes:
  - Ingress
  ingress:
  - from:
    # 1. Only allow traffic from pods with the 'backend' label
    - podSelector:
        matchLabels:
          app: todo-app-backend
    ports:
    # 2. Only allow traffic on the PostgreSQL port
    - protocol: TCP
      port: 5432
---
# Source: todo-app/templates/backend-deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: todo-app-backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: todo-app-backend
---
# Source: todo-app/templates/database-statefulset.yaml
apiVersion: v1
kind: Service
metadata:
  name: todo-app-database
spec:
  ports:
    - port: 5432
  clusterIP: None
  selector:
    app: todo-app-database
---
# Source: todo-app/templates/frontend-deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: todo-app-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: todo-app-frontend
---
# Source: todo-app/templates/backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-backend
  template:
    metadata:
      labels:
        app: todo-app-backend
    spec:
      containers:
      - name: backend
        image: "ghcr.io/wedgehov/todo-api:v1.0.6"
        imagePullPolicy: IfNotPresent
        env:
        - name: FrontendOrigin
          value: https://todo-app-dev.serit.dev
        - name: ConnectionStrings__TodosDb
          value: "Host=todo-app-database;Port=5432;Database=todo_db;Username=todo_user;Password=$(POSTGRES_PASSWORD)"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-app-db-secret
              key: postgres-password
        ports:
        - containerPort: 8080
        resources:
          {}
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
---
# Source: todo-app/templates/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-frontend
  template:
    metadata:
      labels:
        app: todo-app-frontend
    spec:
      containers:
      - name: frontend
        image: "ghcr.io/wedgehov/todo-frontend:v1.0.6"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
# Source: todo-app/templates/database-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-app-database
spec:
  serviceName: todo-app-database
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-database
  template:
    metadata:
      labels:
        app: todo-app-database
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: database
        image: "postgres:16"
        env:
        - name: POSTGRES_USER
          value: "todo_user"
        - name: POSTGRES_DB
          value: "todo_db"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-app-db-secret
              key: postgres-password
        ports:
        - containerPort: 5432
          name: postgres
        resources:
          {}
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: nutanix-volume
      resources:
        requests:
          storage: 1Gi
---
# Source: todo-app/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-app-todo-app-ingress
  annotations:
    # Increase timeouts for long-lived SignalR WebSocket connections
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    # Ensure the NGINX proxy doesn't buffer the response, which helps with real-time streams
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
spec:
  ingressClassName: nginx
  rules:
  - host: "todo-app-dev.serit.dev"
    http:
      paths:
      # Route API and SignalR traffic to the backend service
      - path: /todos
        pathType: Prefix
        backend:
          service:
            name: todo-app-backend
            port:
              number: 80
      - path: /todohub
        pathType: Prefix
        backend:
          service:
            name: todo-app-backend
            port:
              number: 80
      # Route all other traffic (the root path) to the frontend service
      - path: /
        pathType: Prefix
        backend:
          service:
            name: todo-app-frontend
            port:
              number: 80
